Loading the dataset

In [2]:
from keras.datasets import mnist

(X_train, y_train), (X_test, y_test) = mnist.load_data()

Using TensorFlow backend.


In [3]:
from keras.utils import np_utils

Pre-processing

In [4]:
X_train = X_train.reshape(60000,28,28,1)

X_test = X_test.reshape(10000,28,28,1)

y_train = np_utils.to_categorical(y_train)

y_test = np_utils.to_categorical(y_test)

y_train[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

Building the model

In [5]:
from keras.models import Sequential

from keras.layers import Dense, Conv2D, Flatten

In [6]:
model = Sequential()

model.add(Conv2D(64, kernel_size=3, activation='relu', input_shape=(28,28,1)))

model.add(Conv2D(32, kernel_size=3, activation='relu'))

model.add(Flatten())

model.add(Dense(10, activation='softmax'))

Compiling the model

In [7]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

Training the model

In [8]:
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=3)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

Train on 60000 samples, validate on 10000 samples
Epoch 1/3
60000/60000 [==============================] - 138s 2ms/step - loss: 11.2196 - acc: 0.3030 - val_loss: 11.1537 - val_acc: 0.3079
Epoch 2/3
60000/60000 [==============================] - 129s 2ms/step - loss: 11.1723 - acc: 0.3068 - val_loss: 11.1478 - val_acc: 0.3083
Epoch 3/3
60000/60000 [==============================] - 131s 2ms/step - loss: 11.1868 - acc: 0.3059 - val_loss: 11.1779 - val_acc: 0.3065


Making predictions

In [9]:
model.predict(X_test[:4])



array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]], dtype=float32)

In [10]:
y_test[:4]

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)